# Generated by Django 3.1.5 on 2021-08-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('growth', models.PositiveSmallIntegerField()),
                ('eyes_col', models.CharField(choices=[('ГОЛУБОЙ', 'Голубой'), ('СЕРЫЙ', 'Серый'), ('ЗЕЛЕНЫЙ', 'Зеленый'), ('КАРИЙ', 'Карий')], max_length=7)),
                ('hair_col', models.CharField(choices=[('БЛОНДИН', 'Блондин'), ('РЫЖИЙ', 'Рыжий'), ('ТЕМНЫЙ', 'Темный'), ('ЧЕРНЫЙ', 'Черный')], max_length=7)),
                ('freckles', models.CharField(choices=[('МНОГО', 'Много'), ('УМЕРЕННО', 'Умеренно'), ('ЕДИНИЧНЫЕ', 'Единичные'), ('НЕТ', 'Нет')], max_length=9)),
                ('skin_col', models.CharField(choices=[('ОЧЕНЬ БЕЛЫЙ', 'Очень белый'), ('БЕЛЫЙ', 'Белый'), ('СВЕТЛО-БЕЖЕВЫЙ', 'Светло-бежевый'), ('КОРИЧНЕВЫЙ', 'Коричневый'), ('ТЕМНО-КОРИЧНЕВЫЙ', 'Темно-коричневый')], max_length=16)),
                ('redness_during_sunburn', models.BooleanField()),
                ('tanning_character', models.CharField(choices=[('СИЛЬНО СГОРАЕТ', 'Сильно сгорает'), ('УМЕРЕННО СГОРАЕТ', 'Умеренно сгорает'), ('ИНОГДА СГОРАЕТ', 'Иногда сгорает'), ('СГОРАЕТ РЕДКО', 'Сгорает редко'), ('НЕ СГОРАЕТ', 'Не сгорает')], max_length=16)),
                ('rest_in_south', models.CharField(choices=[('10 ДНЕЙ В ГОД', '10 дней в год'), ('20 ДНЕЙ В ГОД', '20 дней в год'), ('БОЛЬШЕ 20 ДНЕЙ В ГОД', 'Больше 20 дней в год'), ('НЕ ОТДЫХАЮ НА ЮГЕ', 'Не отдыхаю на юге')], max_length=20)),
                ('sunscreen_using', models.BooleanField()),
                ('neoplasm_appearance', models.CharField(choices=[('ПОМНЮ С ДЕТСТВА', 'Помню с детства'), ('НЕДАВНО', 'Недавно'), ('НЕ МОГУ ОТВЕТИТЬ', 'Не могу ответить')], max_length=16)),
                ('neoplasm_location', models.CharField(choices=[('ВОЛОСИСТАЯ ЧАСТЬ ГОЛОВЫ', 'Волосистая часть головы'), ('ЛИЦО', 'Лицо'), ('ШЕЯ', 'Шея'), ('ДЕКОЛЬТЕ', 'Декольте'), ('ПЛЕЧО', 'Плечо'), ('ПРЕДПЛЕЧЬЕ', 'Предплечье'), ('КИСТЬ', 'Кисть'), ('НИЖНЯЯ ЧАСТЬ ТУЛОВИЩА', 'Нижняя часть туловища'), ('БЕДРО', 'Бедро'), ('ГОЛЕНЬ', 'Голень'), ('СТОПА', 'Стопа')], max_length=23)),
                ('skin_tumors_in_fam', models.BooleanField(blank=True)),
                ('elem_size', models.PositiveSmallIntegerField(blank=True)),
                ('elem_area', models.PositiveSmallIntegerField(blank=True)),
                ('elem_borders', models.CharField(blank=True, choices=[('ЧЕТКИЕ', 'Четкие'), ('НЕЧЕТКИЕ', 'Нечеткие')], max_length=8)),
                ('elem_color', models.CharField(blank=True, choices=[('КРАСНЫЙ', 'Красный'), ('БЕЖЕВЫЙ', 'Бежевый'), ('КОРИЧНЕВЫЙ', 'Коричневый'), ('ЧЕРНЫЙ', 'Черный')], max_length=10)),
                ('inclusions', models.BooleanField(blank=True)),
                ('elem_symmetry', models.BooleanField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations_register.patient')),
            ],
        ),
    ]
