# Generated by Django 3.1.5 on 2021-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0003_auto_20210815_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_area',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_borders',
            field=models.CharField(blank=True, choices=[('ЧЕТКИЕ', 'Четкие'), ('НЕЧЕТКИЕ', 'Нечеткие')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_color',
            field=models.CharField(blank=True, choices=[('КРАСНЫЙ', 'Красный'), ('БЕЖЕВЫЙ', 'Бежевый'), ('КОРИЧНЕВЫЙ', 'Коричневый'), ('ЧЕРНЫЙ', 'Черный')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
