# Generated by Django 3.1.5 on 2021-08-15 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0004_auto_20210815_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
