# Generated by Django 3.1.5 on 2021-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0006_auto_20210815_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='eyes_col',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='hair_col',
        ),
        migrations.AddField(
            model_name='patient',
            name='eyes_col',
            field=models.CharField(choices=[('ГОЛУБОЙ', 'Голубой'), ('СЕРЫЙ', 'Серый'), ('ЗЕЛЕНЫЙ', 'Зеленый'), ('КАРИЙ', 'Карий')], default='ГОЛУБОЙ', max_length=7),
        ),
        migrations.AddField(
            model_name='patient',
            name='hair_col',
            field=models.CharField(choices=[('БЛОНДИН', 'Блондин'), ('РЫЖИЙ', 'Рыжий'), ('ТЕМНЫЙ', 'Темный'), ('ЧЕРНЫЙ', 'Черный')], default='БЛОНДИН', max_length=7),
        ),
    ]
