# Generated by Django 3.1.5 on 2021-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0010_auto_20210829_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eyes_col',
            field=models.CharField(choices=[('Голубой', 'Голубой'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Карий', 'Карий')], max_length=7),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hair_col',
            field=models.CharField(choices=[('Блондин', 'Блондин'), ('Рыжий', 'Рыжий'), ('Темный', 'Темный'), ('Черный', 'Черный')], max_length=7),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_borders',
            field=models.CharField(blank=True, choices=[('Четкие', 'Четкие'), ('Нечеткие', 'Нечеткие')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='elem_color',
            field=models.CharField(blank=True, choices=[('Красный', 'Красный'), ('Бежевый', 'Бежевый'), ('Коричневый', 'Коричневый'), ('Черный', 'Черный')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='freckles',
            field=models.CharField(choices=[('Много', 'Много'), ('Умеренно', 'Умеренно'), ('Единичные', 'Единичные'), ('Нет', 'Нет')], max_length=9),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='neoplasm_appearance',
            field=models.CharField(choices=[('Помню с детства', 'Помню с детства'), ('Недавно', 'Недавно'), ('Не могу ответить', 'Не могу ответить')], max_length=16),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='neoplasm_location',
            field=models.CharField(choices=[('Волосистая часть головы', 'Волосистая часть головы'), ('Лицо', 'Лицо'), ('Шея', 'Шея'), ('Декольте', 'Декольте'), ('Плечо', 'Плечо'), ('Предплечье', 'Предплечье'), ('Кисть', 'Кисть'), ('Нижняя часть туловища', 'Нижняя часть туловища'), ('Бедро', 'Бедро'), ('Голень', 'Голень'), ('Стопа', 'Стопа')], max_length=23),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rest_in_south',
            field=models.CharField(choices=[('10 дней в год', '10 дней в год'), ('20 дней в год', '20 дней в год'), ('Больше 20 дней в год', 'Больше 20 дней в год'), ('Не отдыхаю на юге', 'Не отдыхаю на юге')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='skin_col',
            field=models.CharField(choices=[('Очень белый', 'Очень белый'), ('Белый', 'Белый'), ('Светло-бежевый', 'Светло-бежевый'), ('Коричневый', 'Коричневый'), ('Темно-коричневый', 'Темно-коричневый')], max_length=16),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='tanning_character',
            field=models.CharField(choices=[('Сильно сгорает', 'Сильно сгорает'), ('Умеренно сгорает', 'Умеренно сгорает'), ('Иногда сгорает', 'Иногда сгорает'), ('Сгорает редко', 'Сгорает редко'), ('Не сгорает', 'Не сгорает')], max_length=16),
        ),
    ]
