# Generated by Django 3.1.5 on 2021-08-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0011_auto_20210829_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='doc_decision',
            field=models.CharField(blank=True, choices=[('Взять гистологическое исследование', 'Взять гистологическое исследование'), ('Провести иссечение элемента', 'Провести иссечение элемента')], max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='reappearance',
            field=models.CharField(blank=True, choices=[('1 мес', '1 мес'), ('3 мес', '3 мес'), ('6 мес', '6 мес'), ('1 год', '1 год')], max_length=5, null=True),
        ),
    ]
