# Generated by Django 3.1.5 on 2021-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0012_auto_20210830_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='reappearance',
            field=models.CharField(blank=True, choices=[('Без повторной явки', 'Без повторной явки'), ('1 мес', '1 мес'), ('3 мес', '3 мес'), ('6 мес', '6 мес'), ('1 год', '1 год')], max_length=18, null=True),
        ),
    ]
