# Generated by Django 3.1.5 on 2021-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0014_auto_20210830_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='neo_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ref_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
