# Generated by Django 3.1.5 on 2021-09-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0015_auto_20210831_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('export_permission', 'Can export data'),)},
        ),
    ]
