# Generated by Django 3.1.5 on 2021-09-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations_register', '0016_auto_20210904_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'permissions': (('export_permission', 'Can export data'),)},
        ),
    ]
